from enum import Enum


class Language(Enum):
    HINDI = "Hindi"
    ENGLISH = "English"
    BENGALI = "Bengali"
    TAMIL = "Tamil"
    TELUGU = "Telugu"
    MARATHI = "Marathi"
    GUJARATI = "Gujarati"
    MALAYALAM = "Malayalam"
    KANNADA = "Kannada"
    ODIA = "Odia"
    PUNJABI = "Punjabi"
    ASSAMESE = "Assamese"
    URDU = "Urdu"
    SINDHI = "Sindhi"
    SANSKRIT = "Sanskrit"
    KASHMIRI = "Kashmiri"
    MAITHILI = "Maithili"
    DOGRI = "Dogri"
    KONKANI = "Konkani"
    BODO = "Bodo"
    MANIPURI = "Manipuri"
    SANTALI = "Santali"
