from enum import Enum


class CampaignStage(Enum):
    CREATED = "CREATED"
    INFLUENCER_FINALIZATION = "INFLUENCER_FINALIZATION"
    SHOOT = "SHOOT"
    POST = "POST"
    FIRST_BILLING = "FIRST_BILLING"
    SECOND_BILLING = "SECOND_BILLING"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"
