from enum import Enum


class CampaignStage(Enum):
    CREATED = "CREATED"
    INFLUENCER_FINALIZED = "INFLUENCER_FINALIZED"
    SHOOT_COMPLETED = "SHOOT_COMPLETED"
    DRAFT_APPROVED = "DRAFT_APPROVED"
    CONTENT_POSTED = "CONTENT_POSTED"
    DAY2_BILLING = "DAY2_BILLING"
    DAY8_BILLING = "DAY8_BILLING"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"
