from enum import Enum


class Niche(Enum):
    FOOD_COOKING = "FOOD_COOKING"
    BEAUTY_SKINCARE = "BEAUTY_SKINCARE"
    TRAVEL_TOURISM = "TRAVEL_TOURISM"
    FASHION = "FASHION"
    HEALTH_FITNESS = "HEALTH_FITNESS"
    TECH_GADGETS = "TECH_GADGETS"
    WEALTH_FINANCE = "WEALTH_FINANCE"
    ENTERTAINMENT = "ENTERTAINMENT"
    LIFESTYLE = "LIFESTYLE"
    MOTIVATIONAL_SPIRITUAL = "MOTIVATIONAL_SPIRITUAL"
    PARENTING_FAMILY = "PARENTING_FAMILY"
    EDUCATION = "EDUCATION"
